name: Build and Deploy document site

on:
  push:
    branches: ["main"]
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build jobs
  build-index:
    runs-on: ubuntu-latest
    name: Build index page
    steps:
      - uses: actions/checkout@v3
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./index
          destination: ./_site
      - name: Archive document
        uses: actions/upload-artifact@v3
        with:
          name: index
          path: ./_site
          retention-days: 1

  build-mdbook:
    runs-on: ubuntu-latest
    name: Build mdbook
    steps:
      - uses: actions/checkout@v3
      - name: Configure mdbook
        working-directory: mdbook
        run: |
          mkdir -p bin
          curl -sSL \
            https://github.com/rust-lang/mdBook/releases/download/v0.4.21/mdbook-v0.4.21-x86_64-unknown-linux-gnu.tar.gz \
          | tar -xz --directory=bin
      - name: Build document
        working-directory: mdbook
        run: |
          bin/mdbook build
      - name: Archive document
        uses: actions/upload-artifact@v3
        with:
          name: mdbook
          path: mdbook/book
          retention-days: 1

  build-docusaurus:
    runs-on: ubuntu-latest
    name: Build docusaurus
    steps:
      - uses: actions/checkout@v3
      - name: Configure docusaurus
        working-directory: docusaurus
        run: npm ci
      - name: Build document
        working-directory: docusaurus
        run: npm run build
      - name: Archive document
        uses: actions/upload-artifact@v3
        with:
          name: docusaurus
          path: docusaurus/build
          retention-days: 1

  build-honkit:
    runs-on: ubuntu-latest
    name: Build honkit
    steps:
      - uses: actions/checkout@v3
      - name: Configure honkit
        working-directory: honkit
        run: npm ci
      - name: Build document
        working-directory: honkit
        run: npm run build
      - name: Archive document
        uses: actions/upload-artifact@v3
        with:
          name: honkit
          path: honkit/_book
          retention-days: 1

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: [build-index, build-mdbook, build-docusaurus, build-honkit]
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Download index page
        uses: actions/download-artifact@v3
        with:
          name: index
          path: _site
      - name: Download mdbook output
        uses: actions/download-artifact@v3
        with:
          name: mdbook
          path: _site/mdbook
      - name: Download docusaurus output
        uses: actions/download-artifact@v3
        with:
          name: docusaurus
          path: _site/docusaurus
      - name: Download honkit output
        uses: actions/download-artifact@v3
        with:
          name: honkit
          path: _site/honkit
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
