name: Build and Deploy document site

on:
  push:
    branches: ["main"]
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build jobs
  build-mdbook:
    runs-on: ubuntu-latest
    name: Build mdbook
    steps:
      - uses: actions/checkout@v3
      - name: Configure mdbook
        working-directory: mdbook
        run: |
          mkdir -p bin
          curl -sSL \
            https://github.com/rust-lang/mdBook/releases/download/v0.4.21/mdbook-v0.4.21-x86_64-unknown-linux-gnu.tar.gz \
          | tar -xz --directory=bin
      - name: Build document
        working-directory: mdbook
        run: |
          bin/mdbook build
      - name: Archive document
        uses: actions/upload-artifact@v3
        with:
          name: mdbook
          path: mdbook/book
          retention-days: 1

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: [build-mdbook]
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Download mdbook output
        uses: actions/download-artifact@v3
        with:
          name: mdbook
          path: _site/mdbook
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
